### PR TITLE
Allow to pass void to `delay`

### LINKED ISSUE #235: `delay` doesn't allow to use `void` in `target`
The effect in the target expects void, a conditional number arrives from doneData - a mismatch in delay types

example:

```ts
delay({
    source: someFirstFx.doneData,
    timeout: 1000,
    target: someSecondFx,
});
```

### PR DESCRIPTION
**Pull request by binjospookie**
fixes #235

not sure it's a good idea to hide the problem with ts-expect-error
on the other hand, no idea how to fix public api without it

### CODE REVIEW

**Review by AlexandrHoroshih — APPROVED** [review]

**Comment by AlexandrHoroshih** [comment]
@binjospookie Can you also add type-tests at https://github.com/effector/patronum/blob/main/test-typings/delay.ts ?
So we don't break it by accident in the future

Simple
```ts
// void events support
{
 const trigger = createEvent<number>()
 const event = createEvent()
 
 delay({
  source: trigger,
  timeout: () => 100,
  target: event,
 })
}
```
will do just fine

**Comment by binjospookie** [comment]
Yes. No problem.

**Comment by sergeysova** [comment]
I think we can wait for the type-tests and release in 1.16

**Comment by binjospookie** [comment]
Done

**Pull request merged**
