### PR TITLE
Snapshot method

### PR DESCRIPTION
**Pull request by igorkamyshev**
### Description

Hello. I create the same operator in Aviasales codebase and after that  I found discussion about it https://github.com/effector/patronum/discussions/96 in this repo. So I decided to move implementation here.

### Checklist for a new method

- [x] Create directory for new method in root in `param-case`
- [x] Place code to `{method-name}/index.js` in CommonJS export in `camelCase` named export
- [x] Add types to `{method-name}/index.d.ts`
- [x] Add tests to `{method-name}/{method-name}.test.ts`
- [x] Add **fork** tests to `{method-name}/{method-name}.fork.test.ts`
- [x] Add **type** tests to `test-typings/{method-name}.ts`
  - Use `// @ts-expect-error` to mark expected type error
  - `import { expectType } from 'tsd'` to check expected return type
- [x] Add documentation in `{method-name}/reade.md`
  - Add header `Patronum/MethodName`
  - Add section with overloads, if have
  - Add `Motivation`, `Formulae`, `Arguments` and `Return` sections for each overload
  - Add useful examples in `Example` section for each overload
- [x] Add section to `README.md` in root
  - Add method to table of contents `- [MethodName](#methodname)`
  - Add section `## [MethodName](/method-name 'Documentation')`
  - With summary and simple example

### CODE REVIEW

**Comment by igorkamyshev** [comment]
Also, I think types of this method is pretty simple, and I am not sure, should I create tests for it?

**Comment by sergeysova** [comment]
@igorkamyshev I think it is better to add type tests

**Comment by igorkamyshev** [comment]
> @igorkamyshev I think it is better to add type tests

Done.

Also, I've updated snapshots for tests. I didn't touch code of the functions, so I think it is just test-flapping. Maybe we can replace snapshot-testing with more stable technics?

**Review by sergeysova — APPROVED** [review]

**Comment by igorkamyshev** [comment]
I found this PR had been approved. So, do you have plans of release it?

**Comment by igorkamyshev** [comment]
@sergeysova sorry for interruption. It looks like ready for release. Could you please merge it? Or should I fix something?

**Pull request merged**
