### PR TITLE
fix(spread): batch store updates on  (#183)

### LINKED ISSUE #183: Batch store updates with `spread`
Since `spread` uses separate `sample` statement for each provided target, effector does not batch store updates
```tsx
spread({
  source: somethingHappened,
  targets: { a: storeA, b: storeB, c: storeC }
})

combine([storeA, storeB, storeC]).watch(console.log)

somethingHappened({ a: 1, b: 2, c: 3 }) // Will re-calculate combine three times
```
Suggested fix is to check target type and, if it's a store, do `store.on(source, ...)` instead of `sample(...)`

### PR DESCRIPTION
**Pull request by Kelin2025**
### Description

Fixes #183

### CODE REVIEW

**Comment by uulaal** [comment]
Looking forward to it!

**Comment by uulaal** [comment]
Seems like not only stores, but events/effects need this improvement. Here is the example where events in `sample` defined before `spread` are not batched: https://share.effector.dev/6QSYhMtt

Maybe it's better to use `forward + map` instead of `sample` for all units? 

```javascript
forward({
  from: hasTargetKey.map((object) => object[targetKey]),
  to: targets[targetKey],
});
```

Example: https://share.effector.dev/kVRQID5q

**Comment by Kelin2025** [comment]
And how do we fix it for events/effects? There is no way to batch it, as I know

**Review by sergeysova — APPROVED** [review]

**Comment by sergeysova** [comment]
@Kelin2025 I have no time to fix that for events. Do you have test suite for this case?

**Comment by Kelin2025** [comment]
I don't think it's possible to batch event calls atm

**Pull request merged**
